DynamicTarpCovers = {
    list = {
        --["CarLights"] = "",    
        --["CarLightsPolice"] = "",    
        --["CarNormal"] = "",    
        --["SmallCar"] = "",    
        ["PickUpVanLights"] = "SVU_DynamicRoofrack_PickupVan",    
        ["PickUpVanLightsPolice"] = "SVU_DynamicRoofrack_PickupVan",     
        ["PickUpVanLightsFire"] = "SVU_DynamicRoofrack_PickupVan",    
        ["PickUpVan"] = "SVU_DynamicRoofrack_PickupVan",    
        --["CarStationWagon"] = "",     
        --["CarStationWagon2"] = "",     
        --["ModernCar"] = "",    
        --["ModernCar02"] = "",     
        --["CarLuxury"] = "PU_Armor_LuxuryCar_vve_animated",     
        --["SmallCar02"] = "PU_Armor_Small02_vve_animated",    
        ["SUV"] = "SVU_DynamicRoofrack_SUV",     
        --["OffRoad"] = "PU_armor_Offroad_vve_animated",    
        ["PickUpVanMccoy"] = "SVU_DynamicRoofrack_PickupVan",    
        --["StepVan"] = "PU_armor_StepVan_vve_animated",    
        --["StepVan_Heralds"] = "PU_armor_StepVan_vve_animated",    
        --["StepVanMail"] = "PU_armor_StepVan_vve_animated",    
        --["StepVan_Scarlet"] = "PU_armor_StepVan_vve_animated",    
        --["VanSeats"] = "PU_armor_VanSeats_vve_animated",    
        --["Van"] = "PU_armor_Van_vve_animated",    
        --["Van_KnoxDisti"] = "PU_armor_Van_vve_animated",    
        --["Van_Transit"] = "PU_armor_Van_vve_animated",    
        --["VanSpiffo"] = "PU_armor_Van_vve_animated",    
        --["VanSpecial"] = "PU_armor_Van_vve_animated",    
        --["Van_MassGenFac"] = "PU_armor_Van_vve_animated",
        --["Van_LectroMax"] = "PU_armor_Van_vve_animated",    
        --["SportsCar"] = "PU_Armor_Sport_vve_animated", 
    },

    modded = {
        ["VVehicleEnhancer"] = {            
            --["CarOldsFull"] = "PU_armor_Normal_vve_animated",
            --["CarNormalPoncho"] = "PU_armor_Normal_vve_animated",
            --["CarLightsStatepolice"] = "PU_armor_Normal_vve_animated", 
            --["CarLightsSheriff"] = "PU_armor_Normal_vve_animated",
            --["CarLightsFireDept"] = "PU_armor_Normal_vve_animated",
            --["CarLightsFireDept2"] = "PU_armor_Normal_vve_animated",
            --["CarOldWagon"] = "PU_armor_SWagon_old_vve_animated",
            --["CarPonchoWagon"] = "PU_armor_SWagon_vve_animated", 
            ["PickUpVanf76"] = "SVU_DynamicRoofrack_PickupVan", 
            ["73cayenne"] = "SVU_DynamicRoofrack_PickupVan",
            --["Vanateam"] = "PU_armor_Van_vve_animated",
            --["Vanboogie"] = "PU_armor_Van_vve_animated",
            --["Boltrs"] = "PU_armor_Small_vve_animated",
            --["SmallCarSwiffer"] = "PU_Armor_Small02_vve_animated",
            --["280sport"] = "PU_armor_Modern02_vve_animated",
            --["StepVanMailupz"] = "PU_armor_StepVan_vve_animated",
        },

        ["STFR"] = {
            --["StepVan_swat"] = "PU_armor_StepVan_vve_animated",
            --["Van_doc"] = "PU_armor_Van_vve_animated",
            --["STFR_87gmcarmoredcar"] = "PU_Armor_87GMC_animated",
        },

        ["STR"] = {
            --["Van_ravencreekdoc"] = "PU_armor_Van_animated",
            --["Van_meadedoc"] = "PU_armor_Van_animated",
            --["Van_jeffersondoc"] = "PU_armor_VanSeats_animated",
            --["STFR_87gmcarmoredcar"] = "PU_Armor_87GMC_animated",
        },

        ["TallerMecanico"] = { 
            --["VanSnakeneta"] = "PU_armor_Van_animated",
            --["VanGenova",   "PU_armor_Van_animated",
            --["CarTaxiArg"] = "PU_armor_Van_animated",
            --["StepVan_Nubasian"] = "PU_armor_StepVan_animated",

            --["Vancmneta",   "PU_armor_Van_animated",
            ["PickUpTruckKelo"] = "SVU_DynamicRoofrack_PickupVan",
            --["StepVanNubAsian"] = "PU_armor_StepVan_animated",
            --["StepVanNumark"] = "PU_armor_StepVan_animated",
            --["StepVanHoneyLove"] = "PU_armor_StepVan_animated",
        },
        ["MysteryMachineOGSN"] = {
            --["VanMysterymachine"] = "PU_armor_Van_animated",
        },
        ["SaveOurStation_KnoxCountry"] = {
            --["SWWS_PickUp"] = "PU_Armor_Pickup2DTruck_animated",
            ["SWWS_PickUpVan"] = "SVU_DynamicRoofrack_PickupVan",
            --["SWWS_Radio"] = "PU_armor_Van_animated",
        },
        ["DashRoamer"] = {
            ["DashRoamer"] = "SVU_DynamicRoofrack_DshRoamer",
        },


        ["DCCars"] = {
            --["CarLuxuryDonny"] = "PU_Armor_LuxuryCar_animated",
            --["CarLuxuryExpresso"] = "PU_Armor_LuxuryCar_animated",
            --["CarLuxuryMach"] = "PU_Armor_LuxuryCar_animated",
            --["CarLuxuryValuIns"] = "PU_Armor_LuxuryCar_animated",

            --["CarNormalDonny"] = "PU_armor_Normal_animated",

            --["CarStationWagonDonny"] = "PU_armor_SWagon_animated",
            --["CarStationWagonBowWow"] = "PU_armor_SWagon_animated",

            --["ModernCar02IWok"] = "PU_Armor_Modern02_animated",

            --["ModernCarDonny"] = "PU_armor_Modern_animated",
            --["ModernCarGoodman"] = "PU_armor_Modern_animated",
            --["ModernCarMarple"] = "PU_armor_Modern_animated",

            --["OffRoadRoxys"] = "PU_armor_Offroad_animated",

            --["PickUpTruckDonny"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckDugout"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckGasTwo"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckSteely"] = "PU_Armor_Pickup2DTruck_animated",

            --["PickUpTruckLightsDonny"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckLightsUSArmy"] = "PU_Armor_Pickup2DTruck_animated",

            ["PickUpVanAitor"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanCarFix"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanChester"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanChuggs"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanSeatFurn"] = "SVU_DynamicRoofrack_PickupVan",

            ["PickUpVanLightsJollyGood"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanLightsUSArmy"] = "SVU_DynamicRoofrack_PickupVan",

            --["SUVFossoil"] = "SVU_DynamicRoofrack_SUV",
            --["SUVInkr"] = "SVU_DynamicRoofrack_SUV",

            --["SmallCar02IWok"] = "PU_Armor_Small02_animated",
            --["SmallCar02TacoDel"] = "PU_Armor_Small02_animated",

            --["SmallCarAwlWork"] = "PU_armor_Small_animated",
            --["SmallCarDonny"] = "PU_armor_Small_animated",

            --["SportsCarDonny"] = "PU_Armor_Sport_animated",
            --["SportsCarDrOids"] = "PU_Armor_Sport_animated",
            --["SportsCarGasTwo"] = "PU_Armor_Sport_animated",
            --["SportsCarPearl"] = "PU_Armor_Sport_animated",
            --["SportsCarPizzaWhirl"] = "PU_Armor_Sport_animated",
            --["SportsCarSpiffos"] = "PU_Armor_Sport_animated",

            --["StepVanBoxPop"] = "PU_armor_StepVan_animated",
            --["StepVanBronks"] = "PU_armor_StepVan_animated",
            --["StepVanDuntio"] = "PU_armor_StepVan_animated",
            --["StepVanEPTools"] = "PU_armor_StepVan_animated",
            --["StepVanEgenerex"] = "PU_armor_StepVan_animated",
            --["StepVanFossoil"] = "PU_armor_StepVan_animated",
            --["StepVanGiga"] = "PU_armor_StepVan_animated",
            --["StepVanGreens"] = "PU_armor_StepVan_animated",
            --["StepVanIWok"] = "PU_armor_StepVan_animated",
            --["StepVanJaysChicken"] = "PU_armor_StepVan_animated",
            --["StepVanKitten"] = "PU_armor_StepVan_animated",
            --["StepVanKnoxKit"] = "PU_armor_StepVan_animated",
            --["StepVanLola"] = "PU_armor_StepVan_animated",
            --["StepVanMilkMonarch"] = "PU_armor_StepVan_animated",
            --["StepVanNewton"] = "PU_armor_StepVan_animated",
            --["StepVanPOC"] = "PU_armor_StepVan_animated",
            --["StepVanPerfick"] = "PU_armor_StepVan_animated",
            --["StepVanPizzaWhirl"] = "PU_armor_StepVan_animated",
            --["StepVanPlonkies"] = "PU_armor_StepVan_animated",
            --["StepVanPopFizz"] = "PU_armor_StepVan_animated",
            --["StepVanSeatFurn"] = "PU_armor_StepVan_animated",
            --["StepVanSkyBlue"] = "PU_armor_StepVan_animated",
            --["StepVanSlurpBurp"] = "PU_armor_StepVan_animated",
            --["StepVanSpiffos"] = "PU_armor_StepVan_animated",
            --["StepVanSunBallz"] = "PU_armor_StepVan_animated",
            --["StepVanUSArmy"] = "PU_armor_StepVan_animated",
            --["StepVanWhisper"] = "PU_armor_StepVan_animated",
            --["StepVanZippee"] = "PU_armor_StepVan_animated",

            --["VanBookNaked"] = "PU_armor_Van_animated",
            --["VanDonny"] = "PU_armor_Van_animated",
            --["VanFashBelle"] = "PU_armor_Van_animated",
            --["VanJaysChicken"] = "PU_armor_Van_animated",
            --["VanKegsplosion"] = "PU_armor_Van_animated",
            --["VanLVBoat"] = "PU_armor_Van_animated",
            --["VanMamas"] = "PU_armor_Van_animated",
            --["VanPharma"] = "PU_armor_Van_animated",
            --["VanPonyRomo"] = "PU_armor_Van_animated",
            --["VanUSArmy"] = "PU_armor_Van_animated",
            --["VanValuIns"] = "PU_armor_Van_animated",

            --["VanLightsChurns"] = "SVU_Armor_VanAmbulance",
            --["VanLightsDonny"] = "SVU_Armor_VanAmbulance",
            --["VanLightsPharma"] = "SVU_Armor_VanAmbulance",
            --["VanLightsSpiffos"] = "SVU_Armor_VanAmbulance",
            --["VanLightsUSArmy"] = "SVU_Armor_VanAmbulance",

            --["VanRadioValuTech"] = "SVU_Armor_VanAmbulance",

            --["VanSeatsCabbage"] = "PU_armor_VanSeats_animated",
            --["VanSeatsDonny"] = "PU_armor_VanSeats_animated",
            --["VanSeatsEden"] = "PU_armor_VanSeats_animated",
            --["VanSeatsSang"] = "PU_armor_VanSeats_animated",
            --["VanSeatsSleepEasy"] = "PU_armor_VanSeats_animated",
            --["VanSeatsTacoDel"] = "PU_armor_VanSeats_animated",
            --["VanSeatsUsedCars"] = "PU_armor_VanSeats_animated",
        },
    },
}