DynamicTarpCovers = {
    list = {
        ["CarNormal"] = "SVU_DynamicRoofrack_Normal",    
        ["SmallCar"] = "SVU_DynamicRoofrack_Small",    
        ["PickUpVanLights"] = "SVU_DynamicRoofrack_PickupVan",    
        ["PickUpVanLightsPolice"] = "SVU_DynamicRoofrack_PickupVan",     
        ["PickUpVanLightsFire"] = "SVU_DynamicRoofrack_PickupVan",    
        ["PickUpVan"] = "SVU_DynamicRoofrack_PickupVan",    
        --["CarStationWagon"] = "",     
        --["CarStationWagon2"] = "",     
        ["ModernCar"] = "SVU_DynamicRoofrack_Normal",    
        ["ModernCar02"] = "SVU_DynamicRoofrack_Modern02",     
        ["CarLuxury"] = "SVU_DynamicRoofrack_Luxury",     
        ["SmallCar02"] = "SVU_DynamicRoofrack_Small",    
        ["SUV"] = "SVU_DynamicRoofrack_SUV",     
        ["OffRoad"] = "SVU_DynamicRoofrack_Offroad",    
        ["PickUpVanMccoy"] = "SVU_DynamicRoofrack_PickupVan",    
        --["StepVan"] = "PU_armor_StepVan_vve_animated",    
        --["StepVan_Heralds"] = "PU_armor_StepVan_vve_animated",    
        --["StepVanMail"] = "PU_armor_StepVan_vve_animated",    
        --["StepVan_Scarlet"] = "PU_armor_StepVan_vve_animated",    
        --["VanSeats"] = "PU_armor_VanSeats_vve_animated",    
        --["Van"] = "PU_armor_Van_vve_animated",    
        --["Van_KnoxDisti"] = "PU_armor_Van_vve_animated",    
        --["Van_Transit"] = "PU_armor_Van_vve_animated",    
        --["VanSpiffo"] = "PU_armor_Van_vve_animated",    
        --["VanSpecial"] = "PU_armor_Van_vve_animated",    
        --["Van_MassGenFac"] = "PU_armor_Van_vve_animated",
        --["Van_LectroMax"] = "PU_armor_Van_vve_animated",    
        ["SportsCar"] = "SVU_DynamicRoofrack_Sport", 
    },

    modded = {
        ["VVehicleEnhancer"] = {            
            ["CarOldsFull"] = "SVU_DynamicRoofrack_Normal",
            ["CarNormalPoncho"] = "SVU_DynamicRoofrack_Normal",
            --["CarOldWagon"] = "PU_armor_SWagon_old_vve_animated",
            --["CarPonchoWagon"] = "PU_armor_SWagon_vve_animated", 
            ["PickUpVanf76"] = "SVU_DynamicRoofrack_PickupVan", 
            ["73cayenne"] = "SVU_DynamicRoofrack_PickupVan",
            --["Vanateam"] = "PU_armor_Van_vve_animated",
            --["Vanboogie"] = "PU_armor_Van_vve_animated",
            ["Boltrs"] = "SVU_DynamicRoofrack_Small",
            ["SmallCarSwiffer"] = "SVU_DynamicRoofrack_Small",
            ["280sport"] = "SVU_DynamicRoofrack_Modern02",
            --["StepVanMailupz"] = "PU_armor_StepVan_vve_animated",
        },

        ["STFR"] = {
            --["StepVan_swat"] = "PU_armor_StepVan_vve_animated",
            --["Van_doc"] = "PU_armor_Van_vve_animated",
            --["STFR_87gmcarmoredcar"] = "PU_Armor_87GMC_animated",
        },

        ["STR"] = {
            --["Van_ravencreekdoc"] = "PU_armor_Van_animated",
            --["Van_meadedoc"] = "PU_armor_Van_animated",
            --["Van_jeffersondoc"] = "PU_armor_VanSeats_animated",
            --["STFR_87gmcarmoredcar"] = "PU_Armor_87GMC_animated",
        },

        ["TallerMecanico"] = { 
            --["VanSnakeneta"] = "PU_armor_Van_animated",
            --["VanGenova",   "PU_armor_Van_animated",
            --["CarTaxiArg"] = "PU_armor_Van_animated",
            --["StepVan_Nubasian"] = "PU_armor_StepVan_animated",

            --["Vancmneta",   "PU_armor_Van_animated",
            ["PickUpTruckKelo"] = "SVU_DynamicRoofrack_PickupVan",
            --["StepVanNubAsian"] = "PU_armor_StepVan_animated",
            --["StepVanNumark"] = "PU_armor_StepVan_animated",
            --["StepVanHoneyLove"] = "PU_armor_StepVan_animated",
        },
        ["MysteryMachineOGSN"] = {
            --["VanMysterymachine"] = "PU_armor_Van_animated",
        },
        ["SaveOurStation_KnoxCountry"] = {
            --["SWWS_PickUp"] = "PU_Armor_Pickup2DTruck_animated",
            ["SWWS_PickUpVan"] = "SVU_DynamicRoofrack_PickupVan",
            --["SWWS_Radio"] = "PU_armor_Van_animated",
        },
        ["DashRoamer"] = {
            ["DashRoamer"] = "SVU_DynamicRoofrack_DshRoamer",
        },


        ["DCCars"] = {
            ["CarLuxuryDonny"] = "SVU_DynamicRoofrack_Luxury",
            ["CarLuxuryExpresso"] = "SVU_DynamicRoofrack_Luxury",
            ["CarLuxuryMach"] = "SVU_DynamicRoofrack_Luxury",
            ["CarLuxuryValuIns"] = "SVU_DynamicRoofrack_Luxury",

            ["CarNormalDonny"] = "SVU_DynamicRoofrack_Normal",

            --["CarStationWagonDonny"] = "PU_armor_SWagon_animated",
            --["CarStationWagonBowWow"] = "PU_armor_SWagon_animated",

            ["ModernCar02IWok"] = "SVU_DynamicRoofrack_Modern02",

            ["ModernCarDonny"] = "SVU_DynamicRoofrack_Normal",
            ["ModernCarGoodman"] = "SVU_DynamicRoofrack_Normal",
            ["ModernCarMarple"] = "SVU_DynamicRoofrack_Normal",

            ["OffRoadRoxys"] = "SVU_DynamicRoofrack_Offroad",

            --["PickUpTruckDonny"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckDugout"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckGasTwo"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckSteely"] = "PU_Armor_Pickup2DTruck_animated",

            --["PickUpTruckLightsDonny"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckLightsUSArmy"] = "PU_Armor_Pickup2DTruck_animated",

            ["PickUpVanAitor"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanCarFix"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanChester"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanChuggs"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanSeatFurn"] = "SVU_DynamicRoofrack_PickupVan",

            ["PickUpVanLightsJollyGood"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanLightsUSArmy"] = "SVU_DynamicRoofrack_PickupVan",

            ["SUVFossoil"] = "SVU_DynamicRoofrack_SUV",
            ["SUVInkr"] = "SVU_DynamicRoofrack_SUV",

            ["SmallCar02IWok"] = "SVU_DynamicRoofrack_Small",
            ["SmallCar02TacoDel"] = "SVU_DynamicRoofrack_Small",

            ["SmallCarAwlWork"] = "SVU_DynamicRoofrack_Small",
            ["SmallCarDonny"] = "SVU_DynamicRoofrack_Small",

            ["SportsCarDonny"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarDrOids"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarGasTwo"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarPearl"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarPizzaWhirl"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarSpiffos"] = "SVU_DynamicRoofrack_Sport",

            --["StepVanBoxPop"] = "PU_armor_StepVan_animated",
            --["StepVanBronks"] = "PU_armor_StepVan_animated",
            --["StepVanDuntio"] = "PU_armor_StepVan_animated",
            --["StepVanEPTools"] = "PU_armor_StepVan_animated",
            --["StepVanEgenerex"] = "PU_armor_StepVan_animated",
            --["StepVanFossoil"] = "PU_armor_StepVan_animated",
            --["StepVanGiga"] = "PU_armor_StepVan_animated",
            --["StepVanGreens"] = "PU_armor_StepVan_animated",
            --["StepVanIWok"] = "PU_armor_StepVan_animated",
            --["StepVanJaysChicken"] = "PU_armor_StepVan_animated",
            --["StepVanKitten"] = "PU_armor_StepVan_animated",
            --["StepVanKnoxKit"] = "PU_armor_StepVan_animated",
            --["StepVanLola"] = "PU_armor_StepVan_animated",
            --["StepVanMilkMonarch"] = "PU_armor_StepVan_animated",
            --["StepVanNewton"] = "PU_armor_StepVan_animated",
            --["StepVanPOC"] = "PU_armor_StepVan_animated",
            --["StepVanPerfick"] = "PU_armor_StepVan_animated",
            --["StepVanPizzaWhirl"] = "PU_armor_StepVan_animated",
            --["StepVanPlonkies"] = "PU_armor_StepVan_animated",
            --["StepVanPopFizz"] = "PU_armor_StepVan_animated",
            --["StepVanSeatFurn"] = "PU_armor_StepVan_animated",
            --["StepVanSkyBlue"] = "PU_armor_StepVan_animated",
            --["StepVanSlurpBurp"] = "PU_armor_StepVan_animated",
            --["StepVanSpiffos"] = "PU_armor_StepVan_animated",
            --["StepVanSunBallz"] = "PU_armor_StepVan_animated",
            --["StepVanUSArmy"] = "PU_armor_StepVan_animated",
            --["StepVanWhisper"] = "PU_armor_StepVan_animated",
            --["StepVanZippee"] = "PU_armor_StepVan_animated",

            --["VanBookNaked"] = "PU_armor_Van_animated",
            --["VanDonny"] = "PU_armor_Van_animated",
            --["VanFashBelle"] = "PU_armor_Van_animated",
            --["VanJaysChicken"] = "PU_armor_Van_animated",
            --["VanKegsplosion"] = "PU_armor_Van_animated",
            --["VanLVBoat"] = "PU_armor_Van_animated",
            --["VanMamas"] = "PU_armor_Van_animated",
            --["VanPharma"] = "PU_armor_Van_animated",
            --["VanPonyRomo"] = "PU_armor_Van_animated",
            --["VanUSArmy"] = "PU_armor_Van_animated",
            --["VanValuIns"] = "PU_armor_Van_animated",

            --["VanLightsChurns"] = "SVU_Armor_VanAmbulance",
            --["VanLightsDonny"] = "SVU_Armor_VanAmbulance",
            --["VanLightsPharma"] = "SVU_Armor_VanAmbulance",
            --["VanLightsSpiffos"] = "SVU_Armor_VanAmbulance",
            --["VanLightsUSArmy"] = "SVU_Armor_VanAmbulance",

            --["VanRadioValuTech"] = "SVU_Armor_VanAmbulance",

            --["VanSeatsCabbage"] = "PU_armor_VanSeats_animated",
            --["VanSeatsDonny"] = "PU_armor_VanSeats_animated",
            --["VanSeatsEden"] = "PU_armor_VanSeats_animated",
            --["VanSeatsSang"] = "PU_armor_VanSeats_animated",
            --["VanSeatsSleepEasy"] = "PU_armor_VanSeats_animated",
            --["VanSeatsTacoDel"] = "PU_armor_VanSeats_animated",
            --["VanSeatsUsedCars"] = "PU_armor_VanSeats_animated",
        },
    },
}