DynamicTarpCovers = {
    list = {
        ["CarNormal"] = "SVU_DynamicRoofrack_Normal",    
        ["SmallCar"] = "SVU_DynamicRoofrack_Small",    
        ["PickUpVanLights"] = "SVU_DynamicRoofrack_PickupVan",    
        ["PickUpVanLightsPolice"] = "SVU_DynamicRoofrack_PickupVan",     
        ["PickUpVanLightsFire"] = "SVU_DynamicRoofrack_PickupVan",    
        ["PickUpVan"] = "SVU_DynamicRoofrack_PickupVan",    
        ["CarStationWagon"] = "SVU_DynamicRoofrack_SWagon",     
        ["CarStationWagon2"] = "SVU_DynamicRoofrack_SWagon",     
        ["ModernCar"] = "SVU_DynamicRoofrack_Normal",    
        ["ModernCar02"] = "SVU_DynamicRoofrack_Modern02",     
        ["CarLuxury"] = "SVU_DynamicRoofrack_Luxury",     
        ["SmallCar02"] = "SVU_DynamicRoofrack_Small",    
        ["SUV"] = "SVU_DynamicRoofrack_SUV",     
        ["OffRoad"] = "SVU_DynamicRoofrack_Offroad",    
        ["PickUpVanMccoy"] = "SVU_DynamicRoofrack_PickupVan",    
        ["StepVan"] = "SVU_DynamicRoofrack_StepVan",    
        ["StepVan_Heralds"] = "SVU_DynamicRoofrack_StepVan",    
        ["StepVanMail"] = "SVU_DynamicRoofrack_StepVan",    
        ["StepVan_Scarlet"] = "SVU_DynamicRoofrack_StepVan",    
        ["VanSeats"] = "SVU_DynamicRoofrack_Van",    
        ["Van"] = "SVU_DynamicRoofrack_Van",    
        ["Van_KnoxDisti"] = "SVU_DynamicRoofrack_Van",    
        ["Van_Transit"] = "SVU_DynamicRoofrack_Van",    
        ["VanSpiffo"] = "SVU_DynamicRoofrack_Van",    
        ["VanSpecial"] = "SVU_DynamicRoofrack_Van",    
        ["Van_MassGenFac"] = "SVU_DynamicRoofrack_Van",
        ["Van_LectroMax"] = "SVU_DynamicRoofrack_Van",    
        ["SportsCar"] = "SVU_DynamicRoofrack_Sport", 
    },

    modded = {
        ["VVehicleEnhancer"] = {            
            ["CarOldsFull"] = "SVU_DynamicRoofrack_Normal",
            ["CarNormalPoncho"] = "SVU_DynamicRoofrack_Normal",
            ["CarOldWagon"] = "SVU_DynamicRoofrack_SWagon",
            ["CarPonchoWagon"] = "SVU_DynamicRoofrack_SWagon", 
            ["PickUpVanf76"] = "SVU_DynamicRoofrack_PickupVan", 
            ["73cayenne"] = "SVU_DynamicRoofrack_PickupVan",
            ["Vanateam"] = "SVU_DynamicRoofrack_Van",
            ["Vanboogie"] = "SVU_DynamicRoofrack_Van",
            ["Boltrs"] = "SVU_DynamicRoofrack_Small",
            ["SmallCarSwiffer"] = "SVU_DynamicRoofrack_Small",
            ["280sport"] = "SVU_DynamicRoofrack_Modern02",
            ["StepVanMailupz"] = "SVU_DynamicRoofrack_StepVan",
        },

        ["STFR"] = {
            ["StepVan_swat"] = "SVU_DynamicRoofrack_StepVan",
            ["Van_doc"] = "SVU_DynamicRoofrack_Van",
            ["STFR_87gmcarmoredcar"] = "SVU_DynamicRoofrack_GMC",
        },

        ["STR"] = {
            ["Van_ravencreekdoc"] = "SVU_DynamicRoofrack_Van",
            ["Van_meadedoc"] = "SVU_DynamicRoofrack_Van",
            ["Van_jeffersondoc"] = "SVU_DynamicRoofrack_Van",
            ["STFR_87gmcarmoredcar"] = "SVU_DynamicRoofrack_GMC",
        },

        ["TallerMecanico"] = { 
            ["VanSnakeneta"] = "SVU_DynamicRoofrack_Van",
            ["VanGenova"] = "SVU_DynamicRoofrack_Van",
            ["CarTaxiArg"] = "SVU_DynamicRoofrack_Van",
            ["StepVan_Nubasian"] = "SVU_DynamicRoofrack_StepVan",

            ["Vancmneta"] = "SVU_DynamicRoofrack_Van",
            ["PickUpTruckKelo"] = "SVU_DynamicRoofrack_PickupVan",
            ["StepVanNubAsian"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanNumark"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanHoneyLove"] = "SVU_DynamicRoofrack_StepVan",
        },
        ["MysteryMachineOGSN"] = {
            ["VanMysterymachine"] = "SVU_DynamicRoofrack_Van",
        },
        ["SaveOurStation_KnoxCountry"] = {
            --["SWWS_PickUp"] = "PU_Armor_Pickup2DTruck_animated",
            ["SWWS_PickUpVan"] = "SVU_DynamicRoofrack_PickupVan",
        },
        ["DashRoamer"] = {
            ["DashRoamer"] = "SVU_DynamicRoofrack_DshRoamer",
        },


        ["DCCars"] = {
            ["CarLuxuryDonny"] = "SVU_DynamicRoofrack_Luxury",
            ["CarLuxuryExpresso"] = "SVU_DynamicRoofrack_Luxury",
            ["CarLuxuryMach"] = "SVU_DynamicRoofrack_Luxury",
            ["CarLuxuryValuIns"] = "SVU_DynamicRoofrack_Luxury",

            ["CarNormalDonny"] = "SVU_DynamicRoofrack_Normal",

            ["CarStationWagonDonny"] = "SVU_DynamicRoofrack_SWagon",
            ["CarStationWagonBowWow"] = "SVU_DynamicRoofrack_SWagon",

            ["ModernCar02IWok"] = "SVU_DynamicRoofrack_Modern02",

            ["ModernCarDonny"] = "SVU_DynamicRoofrack_Normal",
            ["ModernCarGoodman"] = "SVU_DynamicRoofrack_Normal",
            ["ModernCarMarple"] = "SVU_DynamicRoofrack_Normal",

            ["OffRoadRoxys"] = "SVU_DynamicRoofrack_Offroad",

            --["PickUpTruckDonny"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckDugout"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckGasTwo"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckSteely"] = "PU_Armor_Pickup2DTruck_animated",

            --["PickUpTruckLightsDonny"] = "PU_Armor_Pickup2DTruck_animated",
            --["PickUpTruckLightsUSArmy"] = "PU_Armor_Pickup2DTruck_animated",

            ["PickUpVanAitor"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanCarFix"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanChester"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanChuggs"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanSeatFurn"] = "SVU_DynamicRoofrack_PickupVan",

            ["PickUpVanLightsJollyGood"] = "SVU_DynamicRoofrack_PickupVan",
            ["PickUpVanLightsUSArmy"] = "SVU_DynamicRoofrack_PickupVan",

            ["SUVFossoil"] = "SVU_DynamicRoofrack_SUV",
            ["SUVInkr"] = "SVU_DynamicRoofrack_SUV",

            ["SmallCar02IWok"] = "SVU_DynamicRoofrack_Small",
            ["SmallCar02TacoDel"] = "SVU_DynamicRoofrack_Small",

            ["SmallCarAwlWork"] = "SVU_DynamicRoofrack_Small",
            ["SmallCarDonny"] = "SVU_DynamicRoofrack_Small",

            ["SportsCarDonny"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarDrOids"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarGasTwo"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarPearl"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarPizzaWhirl"] = "SVU_DynamicRoofrack_Sport",
            ["SportsCarSpiffos"] = "SVU_DynamicRoofrack_Sport",

            ["StepVanBoxPop"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanBronks"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanDuntio"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanEPTools"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanEgenerex"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanFossoil"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanGiga"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanGreens"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanIWok"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanJaysChicken"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanKitten"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanKnoxKit"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanLola"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanMilkMonarch"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanNewton"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanPOC"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanPerfick"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanPizzaWhirl"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanPlonkies"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanPopFizz"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanSeatFurn"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanSkyBlue"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanSlurpBurp"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanSpiffos"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanSunBallz"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanUSArmy"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanWhisper"] = "SVU_DynamicRoofrack_StepVan",
            ["StepVanZippee"] = "SVU_DynamicRoofrack_StepVan",

            ["VanBookNaked"] = "SVU_DynamicRoofrack_Van",
            ["VanDonny"] = "SVU_DynamicRoofrack_Van",
            ["VanFashBelle"] = "SVU_DynamicRoofrack_Van",
            ["VanJaysChicken"] = "SVU_DynamicRoofrack_Van",
            ["VanKegsplosion"] = "SVU_DynamicRoofrack_Van",
            ["VanLVBoat"] = "SVU_DynamicRoofrack_Van",
            ["VanMamas"] = "SVU_DynamicRoofrack_Van",
            ["VanPharma"] = "SVU_DynamicRoofrack_Van",
            ["VanPonyRomo"] = "SVU_DynamicRoofrack_Van",
            ["VanUSArmy"] = "SVU_DynamicRoofrack_Van",
            ["VanValuIns"] = "SVU_DynamicRoofrack_Van",

            ["VanLightsChurns"] = "SVU_Armor_VanAmbulance",
            ["VanLightsDonny"] = "SVU_Armor_VanAmbulance",
            ["VanLightsPharma"] = "SVU_Armor_VanAmbulance",
            ["VanLightsSpiffos"] = "SVU_Armor_VanAmbulance",
            ["VanLightsUSArmy"] = "SVU_Armor_VanAmbulance",

            ["VanRadioValuTech"] = "SVU_Armor_VanAmbulance",

            ["VanSeatsCabbage"] = "SVU_DynamicRoofrack_Van",
            ["VanSeatsDonny"] = "SVU_DynamicRoofrack_Van",
            ["VanSeatsEden"] = "SVU_DynamicRoofrack_Van",
            ["VanSeatsSang"] = "SVU_DynamicRoofrack_Van",
            ["VanSeatsSleepEasy"] = "SVU_DynamicRoofrack_Van",
            ["VanSeatsTacoDel"] = "SVU_DynamicRoofrack_Van",
            ["VanSeatsUsedCars"] = "SVU_DynamicRoofrack_Van",
        },
    },
}